# Zero Shot No Fine Tuning
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 1-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-1-star.json"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 2-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-2-star.json"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 3-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-3-star.json"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 4-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-4-star.json"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 5-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-5-star.json"

#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 1-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-1-star.json" 
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 2-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-2-star.json"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 3-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-3-star.json"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 4-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-4-star.json"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 5-star Yelp review that could have been written by a human." --dataset_size=40 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-5-star.json"



# Continuation no fine-tuning
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --continuation=True --dataset_size=200 --max_new_tokens=128 --output_path="release/yelp_base_model_continuation.json"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp" --continuation=True --system_prompts="release/yelp_base_model_continuation.json" --dataset_size=200 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_continuation.json"



# 1 shot no finetuning
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp" --k_shot=1 --system_prompt="Generate a new review that mimics the style of the following review(s)." --system_prompts="release/yelp_base_model_continuation.json" --dataset_size=200 --max_new_tokens=128 --output_path="release/yelp_base_model_1_shot.json"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp" --k_shot=1 --system_prompt="Generate a new review that mimics the style of the following review(s)." --system_prompts="release/yelp_base_model_continuation.json"  --dataset_size=200 --max_new_tokens=128 --output_path="release/yelp_abliterated_model_1_shot.json"

# Zero Shot Finetuning
 
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 1-star Yelp review that could have been written by a human." --dataset_size=40  --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-1-star_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 2-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-2-star_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 3-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-3-star_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 4-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-4-star_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --system_prompt="Generate a 5-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128 --output_path="release/yelp_base_model_zero_shot-5-star_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"

#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 1-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-1-star_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 2-star Yelp review that could have been written by a human." --dataset_size=40  --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-2-star_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp"
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 3-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-3-star_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp";
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 4-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-4-star_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp";
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --system_prompt="Generate a 5-star Yelp review that could have been written by a human." --dataset_size=40 --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_zero_shot-5-star_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp";



# Continuation Finetuning
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp"  --continuation=True --system_prompts="release/yelp_base_model_continuation.json" --dataset_size=200 --max_new_tokens=128 --output_path="release/yelp_base_model_continuation_finetuned.json" --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp";
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp"  --continuation=True --dataset_size=200 --system_prompts="release/yelp_base_model_continuation.json" --max_new_tokens=128 --output_path="release/yelp_abliterated_model_continuation_finetuned.json" --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp";

# 1 shot finetuning
#python generate_data.py --model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated" --domain="yelp" --k_shot=1 --system_prompt="Generate a new review that mimics the style of the following review(s)." --dataset_size=200 --peft_path="models/fine_tuned_llama_3-2_1b_abliterated_yelp"  --system_prompts="release/yelp_base_model_continuation.json"  --max_new_tokens=128 --output_path="release/yelp_abliterated_model_1_shot_finetuned.json" --new_model_name="huihui-ai/Llama-3.2-1B-Instruct-abliterated-finetuned-yelp";
#python generate_data.py --model_name="meta-llama/Llama-3.2-1B-Instruct" --domain="yelp" --k_shot=1 --system_prompt="Generate a new review that mimics the style of the following review(s)." --dataset_size=200 --peft_path="models/fine_tuned_llama_3-2_1b_yelp" --max_new_tokens=128  --system_prompts="release/yelp_base_model_continuation.json"  --output_path="release/yelp_base_model_1_shot_finetuned.json" --new_model_name="meta-llama/Llama-3.2-1B-Instruct-finetuned-yelp"